#include "dimensions/phs_rbf_fd_polynomial_assembler_poisson.cpp"
#include "dimensions/rbf_fd_assembler_poisson.cpp"
#include "operators/biharmonic_operator.cpp"
#include "operators/laplacian.cpp"
#include "operators/partial_derivative.cpp"
#include "polynomials/phs_rbf_fd_polynomial_assembler_poisson.cpp"
#include "rbfs/phs_degrees.cpp"
