set(SOURCE_FILES
    assert_test.cpp
    concepts/assertion_condition_test.cpp
    concepts/comparable_test.cpp
    concepts/const_reference_of_test.cpp
    concepts/dense_matrix_test.cpp
    concepts/dense_vector_test.cpp
    concepts/formattable_test.cpp
    concepts/implicitly_convertible_to_test.cpp
    concepts/integral_test.cpp
    concepts/real_scalar_dense_matrix_test.cpp
    concepts/real_scalar_dense_vector_test.cpp
    concepts/real_scalar_test.cpp
    exception_test.cpp
    get_size_test.cpp
    norm_test.cpp
)
