set(SOURCE_FILES
    concepts/assertion_condition_test.cpp
    concepts/const_reference_of_test.cpp
    concepts/convertible_to_test.cpp
    concepts/decayed_to_test.cpp
    concepts/dense_matrix_of_test.cpp
    concepts/dense_matrix_test.cpp
    concepts/dense_vector_of_test.cpp
    concepts/dense_vector_test.cpp
    concepts/eigen_solver_of_test.cpp
    concepts/formattable_test.cpp
    concepts/implicitly_convertible_to_test.cpp
    concepts/integral_test.cpp
    concepts/invocable_as_test.cpp
    concepts/invocable_test.cpp
    concepts/iterative_solver_test.cpp
    concepts/real_scalar_dense_matrix_test.cpp
    concepts/real_scalar_dense_vector_test.cpp
    concepts/real_scalar_sparse_matrix_test.cpp
    concepts/real_scalar_test.cpp
    concepts/reference_of_test.cpp
    concepts/same_as_test.cpp
    concepts/signed_integral_test.cpp
    concepts/sparse_matrix_of_test.cpp
    concepts/sparse_matrix_test.cpp
    exception_test.cpp
    get_size_test.cpp
    isfinite_test.cpp
    norm_test.cpp
    precondition_test.cpp
)
