#include "dense_matrix_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "dense_vector_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "floating_point_dense_matrix_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "floating_point_dense_vector_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "floating_point_test.cpp"  // NOLINT(bugprone-suspicious-include)
