image: ubuntu:focal

stages:
  - Prepare
  - Check
  - Test with Clang
  - Test with GCC
  - Test with MSVC
  - Build Documentation
  - Publish

variables:
  NUM_COLLECT_VERSION: "0.4.0"
  CONAN_USER: "MusicScience37+numerical-collection-cpp"
  SECURE_LOG_LEVEL: debug

include:
  - template: Dependency-Scanning.gitlab-ci.yml
dependency_scanning:
  stage: Check
  needs: []
gemnasium-python-dependency_scanning:
  image:
    name: registry.gitlab.com/gitlab-org/security-products/analyzers/gemnasium-python:2-python-3.9

.retry setting:
  retry:
    max: 2
    when: runner_system_failure

sync pipenv:
  extends: .retry setting
  stage: Prepare
  image: musicscience37/clang-ci:clang12-v4.1
  script:
    - mkdir -p .venv
    - pipenv sync --dev
  cache:
    key:
      prefix: pipenv-linux
      files:
        - Pipfile.lock
    paths:
      - .venv
  artifacts:
    paths:
      - .venv
    expire_in: "1 mos"

line count:
  extends: .retry setting
  stage: Prepare
  dependencies: []
  image: registry.gitlab.com/musicscience37_ci/cloc-docker:v1-4
  script:
    - mkdir -p line_count
    - cloc ./
      --exclude-dir=extern,line_count
      --force-lang=C++,h
      --json --out=line_count/line_count.json
    - cloc ./
      --exclude-dir=extern,line_count,bench,cmake,doc,example,scripts,test
      --force-lang=C++,h
      --json --out=line_count/src_line_count.json
  artifacts:
    paths:
      - line_count
    expire_in: "1 mos"

pre-commit:
  stage: Check
  needs:
    - sync pipenv
  dependencies:
    - sync pipenv
  image: musicscience37/clang-ci:clang12-v4.1
  script:
    - pipenv run pre-commit run --all-files

static analysis:
  extends: .retry setting
  stage: Check
  needs:
    - sync pipenv
  dependencies:
    - sync pipenv
  image: musicscience37/clang-ci:clang12-v4.1
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - apt update
    - apt install -y libstdc++-10-dev
    - pip3 install junit2html
    - mkdir build_static_analysis
    - cd build_static_analysis
    - git clone https://github.com/PSPDFKit-labs/clang-tidy-to-junit.git
    - cd ../
  script:
    - cd build_static_analysis
    - pipenv run conan profile new --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libstdc++11 default
    - pipenv run conan remote add gitlab https://gitlab.com/api/v4/packages/conan
    - pipenv run conan install --build=missing ..
    - cd ../
    - cmake -S ./ -B build_static_analysis
      -DNUM_COLLECT_ENABLE_CLANG_TIDY:BOOL=ON
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_ENABLE_BENCH=ON
      -DNUM_COLLECT_BUILD_EXAMPLES=ON
      -DNUM_COLLECT_ENABLE_CPP_WARNINGS:BOOL=ON
    - cmake --build build_static_analysis
      --target num_collect_clang_tidy
    - scripts/check_clang_tidy.sh build_static_analysis/clang_tidy
  after_script:
    - cd build_static_analysis/clang_tidy
    - cat $(find $1 -name '*.txt') |
      python3 ../clang-tidy-to-junit/clang-tidy-to-junit.py $(dirname $(pwd)) > clang_tidy_junit.xml
    - python3 -m junit2htmlreport clang_tidy_junit.xml clang_tidy_junit.html
  artifacts:
    paths:
      - build_static_analysis
    reports:
      junit:
        - build_static_analysis/clang_tidy/clang_tidy_junit.xml
    when: always
    expire_in: "3 mos"

.release-test-base:
  extends: .retry setting
  needs:
    - sync pipenv
  dependencies:
    - sync pipenv
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - pipenv run conan profile new --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libstdc++11 default
    - pipenv run conan remote add gitlab https://gitlab.com/api/v4/packages/conan
    - pipenv run conan install --build=missing ..
    - cd ../
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Release
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_ENABLE_BENCH=ON
      -DNUM_COLLECT_TEST_BENCHMARKS=ON
      -DNUM_COLLECT_BUILD_EXAMPLES=ON
      -DNUM_COLLECT_TEST_EXAMPLES=ON
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
    - cd $BUILD_DIR
    - cmake --build .
    - ctest -V
  artifacts:
    paths:
      - $BUILD_DIR
      - "*.png"
      - "*.html"
    reports:
      junit:
        - $BUILD_DIR/junit/*.xml
    when: always
    expire_in: "1 mos"

.debug-test-base:
  extends: .release-test-base
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_BUILD_EXAMPLES=ON
      -DNUM_COLLECT_TEST_EXAMPLES=ON
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
    - cd $BUILD_DIR
    - cmake --build .
    - ctest -V

.clang-release-test-base:
  extends: .release-test-base
  before_script:
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - pipenv run conan profile new --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libc++ default
    - pipenv run conan remote add gitlab https://gitlab.com/api/v4/packages/conan
    - pipenv run conan install --build=missing -s build_type=Release ..
    - cd ../

.clang-debug-test-base:
  extends: .debug-test-base
  before_script:
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - pipenv run conan profile new --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libc++ default
    - pipenv run conan remote add gitlab https://gitlab.com/api/v4/packages/conan
    - pipenv run conan install --build=missing -s build_type=Debug ..
    - cd ../

clang coverage:
  extends: .clang-debug-test-base
  stage: Test with Clang
  image: musicscience37/clang-ci:clang12-v4.1
  variables:
    BUILD_DIR: build_clang_coverage
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
      "-DCMAKE_CXX_FLAGS=-fprofile-instr-generate -fcoverage-mapping"
      "-DCMAKE_MODULE_LINKER_FLAGS=-fprofile-instr-generate -fcoverage-mapping"
    - cd $BUILD_DIR
    - mkdir coverage
    - export LLVM_PROFILE_FILE=$(pwd)/coverage/coverage_%p.profraw
    - cmake --build .
    - ctest -V
    - cd ../
    - scripts/collect_llvm_coverage.sh build_clang_coverage
    - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

gcc coverage:
  extends: .release-test-base
  stage: Test with GCC
  image: musicscience37/gcc-ci:gcc10-v4.0
  variables:
    BUILD_DIR: build_gcc_coverage
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
      "-DCMAKE_CXX_FLAGS=--coverage"
      "-DCMAKE_MODULE_LINKER_FLAGS=--coverage"
    - cd $BUILD_DIR
    - cmake --build .
    - ctest -V
    - cd ../
    - scripts/collect_gcc_coverage.sh build_gcc_coverage
  coverage: '/Total:\|\s*(\d+\.?\d+?)%/'

gcc-10-debug:
  extends: .debug-test-base
  stage: Test with GCC
  image: musicscience37/gcc-ci:gcc10-v4.0
  variables:
    BUILD_DIR: build_gcc10_debug

gcc-10-release:
  extends: .release-test-base
  stage: Test with GCC
  image: musicscience37/gcc-ci:gcc10-v4.0
  variables:
    BUILD_DIR: build_gcc10_release

clang-12-debug:
  extends: .clang-debug-test-base
  stage: Test with Clang
  image: musicscience37/clang-ci:clang12-v4.1
  variables:
    BUILD_DIR: build_clang12_debug

clang-12-release:
  extends: .clang-release-test-base
  stage: Test with Clang
  image: musicscience37/clang-ci:clang12-v4.1
  variables:
    BUILD_DIR: build_clang12_release

clang-13-debug:
  extends: .clang-debug-test-base
  stage: Test with Clang
  image: musicscience37/clang-ci:clang13-v4.1
  variables:
    BUILD_DIR: build_clang12_debug

clang-13-release:
  extends: .clang-release-test-base
  stage: Test with Clang
  image: musicscience37/clang-ci:clang13-v4.1
  variables:
    BUILD_DIR: build_clang12_release

clang-12-asan-ubsan:
  extends: .clang-debug-test-base
  stage: Test with Clang
  image: musicscience37/clang-ci:clang12-v4.1
  variables:
    BUILD_DIR: build_clang_asan_ubsan
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
      -DCMAKE_CXX_FLAGS=-fsanitize=address,undefined
      -DCMAKE_MODULE_LINKER_FLAGS=-fsanitize=address,undefined
    - cd $BUILD_DIR
    - cmake --build .
    - ctest -V

clang-12-tsan:
  extends: .clang-debug-test-base
  stage: Test with Clang
  image: musicscience37/clang-ci:clang12-v4.1
  variables:
    BUILD_DIR: build_clang_tsan
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
      -DCMAKE_CXX_FLAGS=-fsanitize=thread
      -DCMAKE_MODULE_LINKER_FLAGS=-fsanitize=thread
    - cd $BUILD_DIR
    - cmake --build .
    - ctest -V

clang-12-conan:
  extends: .retry setting
  stage: Test with Clang
  needs:
    - sync pipenv
  dependencies:
    - sync pipenv
  image: musicscience37/clang-ci:clang12-v4.1
  variables:
    CONAN_CHANNEL: "testing"
  script:
    - pipenv run conan profile new --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libc++ default
    - pipenv run conan remote add gitlab https://gitlab.com/api/v4/packages/conan
    - pipenv run conan create --build missing --test-folder test/conan_package . ${CONAN_USER}/${CONAN_CHANNEL}

clang-12-conan-release:
  extends: .retry setting
  stage: Publish
  needs:
    - sync pipenv
  dependencies:
    - sync pipenv
  image: musicscience37/clang-ci:clang12-v4.1
  variables:
    CONAN_CHANNEL: "stable"
  script:
    - pipenv run conan profile new --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libc++ default
    - pipenv run conan remote add gitlab https://gitlab.com/api/v4/packages/conan
    - pipenv run conan create --build missing --test-folder test/conan_package . ${CONAN_USER}/${CONAN_CHANNEL}
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} pipenv run conan upload -r gitlab num_collect/${NUM_COLLECT_VERSION}@${CONAN_USER}/${CONAN_CHANNEL} --all
  only:
    - develop

msvc-debug:
  extends: .debug-test-base
  tags:
    - shared-windows
    - windows
    - windows-1809
  stage: Test with MSVC
  needs: []
  dependencies: []
  variables:
    BUILD_DIR: build_msvc_debug
  before_script:
    - Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
    - choco install cmake -y --installargs 'ADD_CMAKE_TO_PATH=System'
    - choco install python --version=3.9.10 -y
    - RefreshEnv
    - pip install pipenv
    - pipenv sync
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - pipenv run conan profile new --detect default
    - pipenv run conan remote add gitlab https://gitlab.com/api/v4/packages/conan
    - pipenv run conan install --build=missing -s build_type=Debug ..
    - cd ../
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_ENABLE_BENCH=ON
      -DNUM_COLLECT_TEST_BENCHMARKS=OFF
      -DNUM_COLLECT_BUILD_EXAMPLES=ON
      -DNUM_COLLECT_TEST_EXAMPLES=OFF
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
      "-DCMAKE_CXX_FLAGS=/DFMT_USE_NONTYPE_TEMPLATE_PARAMETERS=0"
    - cd $BUILD_DIR
    - cmake --build . --config Debug --parallel 3
    - ctest -V --build-config Debug
  allow_failure: true

msvc-release:
  extends: .release-test-base
  tags:
    - shared-windows
    - windows
    - windows-1809
  stage: Test with MSVC
  needs: []
  dependencies: []
  variables:
    BUILD_DIR: build_msvc
  before_script:
    - Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
    - choco install cmake -y --installargs 'ADD_CMAKE_TO_PATH=System'
    - choco install python --version=3.9.10 -y
    - RefreshEnv
    - pip install pipenv
    - pipenv sync
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - pipenv run conan profile new --detect default
    - pipenv run conan remote add gitlab https://gitlab.com/api/v4/packages/conan
    - pipenv run conan install --build=missing -s build_type=Release ..
    - cd ../
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Release
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_ENABLE_BENCH=ON
      -DNUM_COLLECT_TEST_BENCHMARKS=OFF
      -DNUM_COLLECT_BUILD_EXAMPLES=ON
      -DNUM_COLLECT_TEST_EXAMPLES=OFF
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
      "-DCMAKE_CXX_FLAGS=/DFMT_USE_NONTYPE_TEMPLATE_PARAMETERS=0"
    - cd $BUILD_DIR
    - cmake --build . --config Release --parallel 3
    - ctest -V --build-config Release
  allow_failure: true

doc:
  extends: .retry setting
  stage: Build Documentation
  needs:
    - sync pipenv
  dependencies:
    - sync pipenv
  image: musicscience37/sphinx-doxygen:clang12-v4.1
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build_doc
    - cd build_doc
    - pipenv run conan profile new --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libstdc++11 default
    - pipenv run conan remote add gitlab https://gitlab.com/api/v4/packages/conan
    - pipenv run conan install --build=missing ..
    - cd ../
    - cmake -S ./ -B build_doc
      -DNUM_COLLECT_BUILD_DOC:BOOL=ON
    - cmake --build build_doc --target num_collect_doc
  artifacts:
    paths:
      - build_doc
    when: always
    expire_in: "3 mos"

pages:
  extends: .retry setting
  stage: Publish
  only:
    - develop
  needs:
    - doc
  dependencies:
    - doc
  script:
    - rm -rf public
    - mv build_doc/doc/html public
  artifacts:
    paths:
      - public
