image: ubuntu:focal

stages:
  - test
  - deploy
  - release

variables:
  SECURE_LOG_LEVEL: debug

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
dependency_scanning:
  needs: []
sast:
  needs: []

.retry setting:
  retry: 1

line count:
  extends: .retry setting
  stage: test
  needs: []
  image: registry.gitlab.com/musicscience37projects/docker/scc-docker
  script:
    - mkdir -p line_count
    - scc
      --format-multi "tabular:stdout,html:line_count/line_count.html"
      .
    - scc
      --format-multi "openmetrics:line_count/cpp_line_count.txt"
      -i h,cpp
      .
    - scc
      --format-multi "tabular:stdout,html:line_count/src_line_count.html"
      --by-file -s complexity
      include src
  artifacts:
    paths:
      - line_count
    reports:
      metrics:
        - "line_count/cpp_line_count.txt"
    expire_in: "1 mos"
  interruptible: true

complexity:
  extends: .retry setting
  stage: test
  needs: []
  image: musicscience37/clang-ci:clang20
  script:
    - poetry config virtualenvs.in-project true
    - poetry env use 3.13
    - poetry install
    - mkdir -p complexity
    - poetry run lizard -o complexity/complexity_per_function.html include
    - poetry run lizard -o complexity/result.txt -E duplicate include
  cache:
    key:
      prefix: cache-${CI_JOB_NAME}
      files:
        - poetry.lock
    paths:
      - .venv
  artifacts:
    paths:
      - complexity
    expire_in: "1 mos"
  interruptible: true

pre-commit:
  stage: test
  needs: []
  image: musicscience37/clang-ci:clang20
  script:
    - poetry config virtualenvs.in-project true
    - poetry env use 3.13
    - poetry install
    - poetry run pre-commit run --all-files
  cache:
    key:
      prefix: cache-${CI_JOB_NAME}
      files:
        - poetry.lock
    paths:
      - .venv
  interruptible: true

spell check:
  stage: test
  needs: []
  image: node
  script:
    - npm install -g cspell
    - cspell lint
      "**/*.h"
      "**/*.cpp"
      "**/*.py"
      "**/*.cmake"
      "**/*.txt"
      "**/*.md"
      "**/*.rst"
      "**/*.puml"
      "**/*.bib"
      "**/*.yaml"
      "**/*.json"
      "**/*.sh"
      --exclude "**/*.approved.*"
  interruptible: true

.test linux base:
  stage: test
  needs: []
  parallel:
    matrix:
      - COMPILER_TYPE: ["clang20"]
        IMAGE_PATH: "musicscience37/clang-ci"
        TEST_TYPE: "release"
  image: ${IMAGE_PATH}:${COMPILER_TYPE}
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    BUILD_DIR: build_${COMPILER_TYPE}_${TEST_TYPE}
    CCACHE_DIR: ${CI_PROJECT_DIR}/.ccache
    CCACHE_COMPILERCHECK: content
    CCACHE_MAXSIZE: 1G
    VCPKG_DEFAULT_BINARY_CACHE: ${CI_PROJECT_DIR}/.vcpkg-cache
    POETRY_CACHE_DIR: ${CI_PROJECT_DIR}/.poetry-cache
    PLAYWRIGHT_BROWSERS_PATH: ${CI_PROJECT_DIR}/.playwright
  before_script:
    - poetry config virtualenvs.in-project true
    - poetry env use 3.13
    - poetry install
    - mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
    - mkdir $BUILD_DIR
    - poetry run playwright install --only-shell --with-deps chromium
    - poetry run plotly_get_chrome -y
  script:
    - poetry run python ./scripts/ci_linux_test.py
      --compiler_type $COMPILER_TYPE --test_type $TEST_TYPE --build_dir $BUILD_DIR
  cache:
    - key:
        prefix: poetry-${COMPILER_TYPE}-${TEST_TYPE}
        files:
          - poetry.lock
      paths:
        - .poetry-cache
    - key:
        prefix: vcpkg-${COMPILER_TYPE}-${TEST_TYPE}
        files:
          - vcpkg-configuration.json
      paths:
        - .vcpkg-cache
    - key: playwright-${COMPILER_TYPE}-${TEST_TYPE}
      paths:
        - .playwright
    - key: ccache-${COMPILER_TYPE}-${TEST_TYPE}
      paths:
        - .ccache
  artifacts:
    paths:
      - $BUILD_DIR/bench
      - $BUILD_DIR/junit
      - $BUILD_DIR/temp_test
      - "*.png"
      - "*.html"
      - test # For outputs of ApprovalTest.
    reports:
      junit:
        - $BUILD_DIR/junit/*.xml
    when: always
    expire_in: "1 mos"
  interruptible: true

test linux:
  extends: .test linux base
  parallel:
    matrix:
      - COMPILER_TYPE: "gcc13"
        IMAGE_PATH: "musicscience37/gcc-ci"
        TEST_TYPE: ["debug", "release", "bench"]
      - COMPILER_TYPE: ["clang19", "clang20"]
        IMAGE_PATH: "musicscience37/clang-ci"
        TEST_TYPE: ["debug", "release", "bench"]
  script:
    - poetry run python ./scripts/ci_linux_test.py
      --compiler_type $COMPILER_TYPE --test_type $TEST_TYPE --build_dir $BUILD_DIR

static analysis:
  extends: .test linux base
  parallel:
    matrix:
      - COMPILER_TYPE: "clang20"
        IMAGE_PATH: "musicscience37/clang-ci"
        TEST_TYPE: "static_analysis"
  variables:
    BUILD_TYPE: Debug
    BUILD_DIR: build_static_analysis
  script:
    - cd $BUILD_DIR
    - cmake ..
      -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
      -DVCPKG_TARGET_TRIPLET=x64-linux-llvm
      -DVCPKG_HOST_TRIPLET=x64-linux-llvm
      -DCMAKE_CXX_FLAGS=-stdlib=libc++
      -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_ENABLE_BENCH=ON
      -DNUM_COLLECT_ENABLE_HEAVY_BENCH=OFF
      -DNUM_COLLECT_BUILD_EXAMPLES=ON
      -DNUM_COLLECT_BUILD_EXPERIMENTS=ON
      -DNUM_COLLECT_ENABLE_CPP_WARNINGS:BOOL=ON
    - cd ..
    - poetry run clang-tidy-checker -b ${BUILD_DIR} --cache_dir ./.clang-tidy-cache
  cache:
    - key:
        prefix: poetry-${COMPILER_TYPE}-${TEST_TYPE}
        files:
          - poetry.lock
      paths:
        - .poetry-cache
    - key:
        prefix: vcpkg-${COMPILER_TYPE}-${TEST_TYPE}
        files:
          - vcpkg-configuration.json
      paths:
        - .vcpkg-cache
    - key: clang-tidy-checker-${COMPILER_TYPE}-${TEST_TYPE}
      paths:
        - .clang-tidy-cache

clang coverage:
  extends: .test linux base
  parallel:
    matrix:
      - COMPILER_TYPE: "clang20"
        IMAGE_PATH: "musicscience37/clang-ci"
        TEST_TYPE: "coverage"
  variables:
    BUILD_TYPE: Debug
    BUILD_DIR: build_clang_coverage
  script:
    - cd $BUILD_DIR
    - cmake ..
      -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
      -DVCPKG_TARGET_TRIPLET=x64-linux-llvm
      -DVCPKG_HOST_TRIPLET=x64-linux-llvm
      -DCMAKE_BUILD_TYPE=Debug
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
      "-DCMAKE_CXX_FLAGS=-stdlib=libc++ -fprofile-instr-generate -fcoverage-mapping"
      "-DCMAKE_MODULE_LINKER_FLAGS=-fprofile-instr-generate -fcoverage-mapping"
      -DNUM_COLLECT_ENABLE_CCACHE:BOOL=ON
    - mkdir coverage
    - export LLVM_PROFILE_FILE=$(pwd)/coverage/coverage_%p.profraw
    - cmake --build .
    - ctest -V
    - cd ../
    - scripts/collect_llvm_coverage.sh build_clang_coverage
    - poetry run lcov_cobertura $BUILD_DIR/coverage/coverage --output $BUILD_DIR/coverage.xml
    - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  coverage: '/[^\s]+%\s+\d+\s+\d+\s+\s[^\s]+%/'
  artifacts:
    paths:
      - $BUILD_DIR/bench
      - $BUILD_DIR/junit
      - $BUILD_DIR/temp_test
      - $BUILD_DIR/coverage
      - "*.png"
      - "*.html"
    reports:
      junit:
        - $BUILD_DIR/junit/*.xml
      coverage_report:
        coverage_format: cobertura
        path: $BUILD_DIR/coverage.xml
    when: always
    expire_in: "1 mos"

test asan ubsan:
  extends: .test linux base
  parallel:
    matrix:
      - COMPILER_TYPE: "clang20"
        IMAGE_PATH: "musicscience37/clang-ci"
        TEST_TYPE: "asan_ubsan"
  variables:
    ASAN_OPTIONS: "alloc_dealloc_mismatch=0"
  script:
    - poetry run python ./scripts/ci_linux_test.py
      --compiler_type $COMPILER_TYPE --test_type $TEST_TYPE --build_dir $BUILD_DIR

test msvc release:
  stage: test
  needs: []
  tags:
    - ms37win
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    BUILD_TYPE: Release
    BUILD_DIR: build_msvc_release
    CCACHE_DIR: ${CI_PROJECT_DIR}/.ccache
    CCACHE_COMPILERCHECK: content
    CCACHE_MAXSIZE: 1G
    VCPKG_DEFAULT_BINARY_CACHE: ${CI_PROJECT_DIR}/.vcpkg-cache
    # workaround in https://github.com/python-poetry/poetry/issues/1917#issuecomment-1235998997
    PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
    POETRY_CACHE_DIR: ${CI_PROJECT_DIR}/.poetry-cache
  before_script:
    - New-Item -ItemType Directory -Force -Path $VCPKG_DEFAULT_BINARY_CACHE
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install --only test
    - .\vcpkg\bootstrap-vcpkg.bat
    - mkdir $BUILD_DIR
  script:
    - cd $BUILD_DIR
    - cmd.exe /C ..\scripts\ci_win.cmd
  cache:
    - key:
        prefix: poetry-${CI_JOB_NAME}
        files:
          - poetry.lock
      paths:
        - .poetry-cache
    - key:
        prefix: vcpkg-${CI_JOB_NAME}
        files:
          - vcpkg-configuration.json
      paths:
        - .vcpkg-cache
    - key: ccache-${CI_JOB_NAME}
      paths:
        - .ccache
  artifacts:
    paths:
      - $BUILD_DIR/bench
      - $BUILD_DIR/junit
      - $BUILD_DIR/temp_test
      - "*.png"
      - "*.html"
      - test # For outputs of ApprovalTest.
    reports:
      junit:
        - $BUILD_DIR/junit/*.xml
    when: always
    expire_in: "1 mos"
  interruptible: true

doc:
  extends: .test linux base
  parallel:
    matrix:
      - COMPILER_TYPE: "clang20"
        IMAGE_PATH: "musicscience37/sphinx-doxygen"
        TEST_TYPE: "doc"
  variables:
    BUILD_TYPE: Release
    BUILD_DIR: build_doc
  script:
    - cd $BUILD_DIR
    - cmake ..
      -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
      -DNUM_COLLECT_BUILD_DOC:BOOL=ON
    - cmake --build . --target num_collect_doc
  artifacts:
    paths:
      - build_doc/doc
    when: always
    expire_in: "1 mos"
  interruptible: true

pages main:
  stage: deploy
  only:
    - main
  needs:
    - "doc: [clang20, musicscience37/sphinx-doxygen, doc]"
    - "clang coverage: [clang20, musicscience37/clang-ci, coverage]"
    - line count
    - complexity
  dependencies:
    - "doc: [clang20, musicscience37/sphinx-doxygen, doc]"
    - "clang coverage: [clang20, musicscience37/clang-ci, coverage]"
    - line count
    - complexity
  image: alpine
  script:
    - rm -rf public
    - mv build_doc/doc/html public
    - mv build_clang_coverage/coverage/html public/coverage
    - mv line_count public/line_count
    - mv complexity public/complexity
  artifacts:
    paths:
      - public
  pages: true

pages release:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^v/
  needs:
    - "doc: [clang20, musicscience37/sphinx-doxygen, doc]"
  dependencies:
    - "doc: [clang20, musicscience37/sphinx-doxygen, doc]"
  image: alpine
  script:
    - rm -rf public
    - mv build_doc/doc/html public
  artifacts:
    paths:
      - public
  pages:
    path_prefix: $CI_COMMIT_TAG
    expire_in: never

release:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  stage: release
  needs: []
  rules:
    - if: $CI_COMMIT_TAG =~ /^v/
  script:
    - echo "This is a release job."
  release:
    tag_name: $CI_COMMIT_TAG
    name: "$CI_COMMIT_TAG"
    description: "./doc/sphinx/src/release_notes/${CI_COMMIT_TAG}.md"
