image: ubuntu:focal

stages:
  - Prepare
  - Check
  - Test with Clang
  - Test with GCC
  - Build Documentation
  - Publish

.retry setting:
  retry:
    max: 2
    when: runner_system_failure

line count:
  extends: .retry setting
  stage: Prepare
  dependencies: []
  image: registry.gitlab.com/musicscience37_ci/cloc-docker:v1-2
  script:
    - mkdir -p line_count
    - cloc ./
      --exclude-dir=extern,line_count
      --force-lang=C++,h
      --json --out=line_count/line_count.json
    - cloc ./
      --exclude-dir=extern,line_count,bench,cmake,doc,example,scripts,test
      --force-lang=C++,h
      --json --out=line_count/src_line_count.json
  artifacts:
    paths:
      - line_count
    expire_in: "1 mos"

static analysis:
  extends: .retry setting
  stage: Check
  needs:
    - line count
  dependencies: []
  image: musicscience37/clang-ci:clang10-v3.0
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - pip3 install junit2html
    - mkdir build_static_analysis
    - cd build_static_analysis
    - git clone https://github.com/PSPDFKit-labs/clang-tidy-to-junit.git
    - cd ../
  script:
    - cmake -S ./ -B build_static_analysis
      -DNUM_COLLECT_ENABLE_CLANG_TIDY:BOOL=ON
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_ENABLE_BENCH=ON
      -DNUM_COLLECT_ENABLE_CPP_WARNINGS:BOOL=ON
    - cmake --build build_static_analysis
      --target num_collect_clang_tidy
    - scripts/check_clang_tidy.sh build_static_analysis/clang_tidy
  after_script:
    - cd build_static_analysis/clang_tidy
    - cat $(find $1 -name '*.txt') |
      python3 ../clang-tidy-to-junit/clang-tidy-to-junit.py $(dirname $(pwd)) > clang_tidy_junit.xml
    - python3 -m junit2htmlreport clang_tidy_junit.xml clang_tidy_junit.html
  artifacts:
    paths:
      - build_static_analysis
    reports:
      junit:
        - build_static_analysis/clang_tidy/clang_tidy_junit.xml
    when: always
    expire_in: "3 mos"

.release-test-base:
  extends: .retry setting
  needs:
    - line count
  dependencies: []
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir $BUILD_DIR
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Release
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_ENABLE_BENCH=ON
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
    - cd $BUILD_DIR
    - ctest -V -M Experimental -T Configure -T Build -T Test
    - ctest -M Experimental -T Submit
  artifacts:
    paths:
      - $BUILD_DIR
    reports:
      junit:
        - $BUILD_DIR/junit/*.xml
    when: always
    expire_in: "1 mos"

.debug-test-base:
  extends: .release-test-base
  script:
    - mkdir $BUILD_DIR
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_ENABLE_BENCH=ON
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
    - cd $BUILD_DIR
    - ctest -V -M Experimental -T Configure -T Build -T Test -T MemCheck
    - ctest -M Experimental -T Submit

clang coverage:
  extends: .release-test-base
  stage: Test with Clang
  image: musicscience37/clang-ci:clang10-v3.0
  variables:
    BUILD_DIR: build_clang_coverage
  script:
    - mkdir $BUILD_DIR
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
      "-DCMAKE_CXX_FLAGS=-fprofile-instr-generate -fcoverage-mapping"
      "-DCMAKE_MODULE_LINKER_FLAGS=-fprofile-instr-generate -fcoverage-mapping"
    - cd $BUILD_DIR
    - mkdir coverage
    - export LLVM_PROFILE_FILE=$(pwd)/coverage/coverage_%p.profraw
    - ctest -V -M Experimental -T Configure -T Build -T Test
    - ctest -M Experimental -T Submit
    - cd ../
    - scripts/collect_llvm_coverage.sh build_clang_coverage
  coverage: '/Line Coverage: \d+\.\d+/'

gcc coverage:
  extends: .release-test-base
  stage: Test with GCC
  image: musicscience37/gcc-ci:gcc10-v3.0
  variables:
    BUILD_DIR: build_gcc_coverage
  script:
    - mkdir $BUILD_DIR
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
      "-DCMAKE_CXX_FLAGS=--coverage"
      "-DCMAKE_MODULE_LINKER_FLAGS=--coverage"
    - cd $BUILD_DIR
    - ctest -V -M Experimental -T Configure -T Build -T Test
    - ctest -M Experimental -T Coverage || true
    - ctest -M Experimental -T Submit
    - cd ../
    - scripts/collect_gcc_coverage.sh build_gcc_coverage
  coverage: '/Total:\|\s*(\d+\.?\d+?)%/'

gcc-10-debug:
  extends: .debug-test-base
  stage: Test with GCC
  image: musicscience37/gcc-ci:gcc10-v3.0
  variables:
    BUILD_DIR: build_gcc10_debug

gcc-10-release:
  extends: .release-test-base
  stage: Test with GCC
  image: musicscience37/gcc-ci:gcc10-v3.0
  variables:
    BUILD_DIR: build_gcc10_release
