image: ubuntu:focal

stages:
  - Prepare
  - Check
  - Test with Clang
  - Test with GCC
  - Test with MSVC
  - Build Documentation
  - Publish

variables:
  NUM_COLLECT_VERSION: "0.4.1"
  CONAN_USER: "MusicScience37+numerical-collection-cpp"
  SECURE_LOG_LEVEL: debug

include:
  - template: Dependency-Scanning.gitlab-ci.yml
dependency_scanning:
  stage: Check
  needs: []
gemnasium-python-dependency_scanning:
  image:
    name: registry.gitlab.com/gitlab-org/security-products/analyzers/gemnasium-python:2-python-3.9

.retry setting:
  retry:
    max: 2
    when: runner_system_failure

sync pipenv:
  extends: .retry setting
  stage: Prepare
  image: musicscience37/clang-ci:clang14-v5.0
  script:
    - mkdir -p .venv
    - pipenv sync --dev
  cache:
    key:
      prefix: pipenv-linux
      files:
        - Pipfile.lock
    paths:
      - .venv
  artifacts:
    paths:
      - .venv
    expire_in: "1 mos"

line count:
  extends: .retry setting
  stage: Prepare
  dependencies: []
  image: registry.gitlab.com/musicscience37/cloc-docker:v2-0
  script:
    - mkdir -p line_count
    - cloc ./
      --exclude-dir=extern,line_count
      --force-lang=C++,h
      --json --out=line_count/line_count.json
    - cloc ./
      --exclude-dir=extern,line_count,bench,cmake,doc,example,scripts,test
      --force-lang=C++,h
      --json --out=line_count/src_line_count.json
  artifacts:
    paths:
      - line_count
    expire_in: "1 mos"

pre-commit:
  stage: Check
  needs:
    - sync pipenv
  dependencies:
    - sync pipenv
  image: musicscience37/clang-ci:clang14-v5.0
  script:
    - pipenv run pre-commit run --all-files

static analysis:
  extends: .retry setting
  stage: Check
  needs:
    - sync pipenv
  dependencies:
    - sync pipenv
  image: musicscience37/clang-ci:clang14-v5.0
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - apt update
    - apt install -y libstdc++-10-dev
    - pip3 install junit2html
    - mkdir build_static_analysis
    - cd build_static_analysis
    - git clone https://github.com/PSPDFKit-labs/clang-tidy-to-junit.git
    - cd ../
  script:
    - cd build_static_analysis
    - pipenv run conan profile new --force --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libstdc++11 default
    - pipenv run conan remote add -f gitlab https://gitlab.com/api/v4/packages/conan
    - pipenv run conan install --build missing -o num_collect:requirements_for_tests=True ..
    - cd ../
    - cmake -S ./ -B build_static_analysis
      -DNUM_COLLECT_ENABLE_CLANG_TIDY:BOOL=ON
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_ENABLE_BENCH=ON
      -DNUM_COLLECT_BUILD_EXAMPLES=ON
      -DNUM_COLLECT_ENABLE_CPP_WARNINGS:BOOL=ON
    - cmake --build build_static_analysis
      --target num_collect_clang_tidy
    - scripts/check_clang_tidy.sh build_static_analysis/clang_tidy
  after_script:
    - cd build_static_analysis/clang_tidy
    - cat $(find $1 -name '*.txt') |
      python3 ../clang-tidy-to-junit/clang-tidy-to-junit.py $(dirname $(pwd)) > clang_tidy_junit.xml
    - python3 -m junit2htmlreport clang_tidy_junit.xml clang_tidy_junit.html
  artifacts:
    paths:
      - build_static_analysis
    reports:
      junit:
        - build_static_analysis/clang_tidy/clang_tidy_junit.xml
    when: always
    expire_in: "3 mos"

.release-test-base:
  extends: .retry setting
  needs:
    - sync pipenv
  dependencies:
    - sync pipenv
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CCACHE_DIR: ${CI_PROJECT_DIR}/.cache
    CCACHE_COMPILERCHECK: content
    CONAN_USER_HOME: ${CI_PROJECT_DIR}
  before_script:
    - apt-get update && apt-get install -y ccache
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - pipenv run conan profile new --force --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libstdc++11 default
    - pipenv run conan remote add -f gitlab https://gitlab.com/api/v4/packages/conan
    - pipenv run conan install --build missing -o num_collect:requirements_for_tests=True ..
    - cd ../
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Release
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_ENABLE_UNIT_TESTS=ON
      -DNUM_COLLECT_ENABLE_INTEG_TESTS=ON
      -DNUM_COLLECT_ENABLE_BENCH=OFF
      -DNUM_COLLECT_TEST_BENCHMARKS=OFF
      -DNUM_COLLECT_BUILD_EXAMPLES=OFF
      -DNUM_COLLECT_TEST_EXAMPLES=OFF
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
      -DNUM_COLLECT_ENABLE_CCACHE:BOOL=ON
    - cd $BUILD_DIR
    - cmake --build .
    - ctest -V
  cache:
    key: cache-${CI_JOB_NAME}
    paths:
      - .cache
      - .conan
  artifacts:
    paths:
      - $BUILD_DIR
      - "*.png"
      - "*.html"
    reports:
      junit:
        - $BUILD_DIR/junit/*.xml
    when: always
    expire_in: "1 mos"

.bench-base:
  extends: .release-test-base
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Release
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_ENABLE_UNIT_TESTS=OFF
      -DNUM_COLLECT_ENABLE_INTEG_TESTS=OFF
      -DNUM_COLLECT_ENABLE_BENCH=ON
      -DNUM_COLLECT_TEST_BENCHMARKS=ON
      -DNUM_COLLECT_BUILD_EXAMPLES=ON
      -DNUM_COLLECT_TEST_EXAMPLES=ON
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
      -DNUM_COLLECT_ENABLE_CCACHE:BOOL=ON
    - cd $BUILD_DIR
    - cmake --build .
    - ctest -V

.debug-test-base:
  extends: .release-test-base
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_ENABLE_UNIT_TESTS=ON
      -DNUM_COLLECT_ENABLE_INTEG_TESTS=ON
      -DNUM_COLLECT_ENABLE_BENCH=OFF
      -DNUM_COLLECT_TEST_BENCHMARKS=OFF
      -DNUM_COLLECT_BUILD_EXAMPLES=ON
      -DNUM_COLLECT_TEST_EXAMPLES=ON
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
      -DNUM_COLLECT_ENABLE_CCACHE:BOOL=ON
    - cd $BUILD_DIR
    - cmake --build .
    - ctest -V

.clang-release-test-base:
  extends: .release-test-base
  before_script:
    - apt-get update && apt-get install -y ccache
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - pipenv run conan profile new --force --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libc++ default
    - pipenv run conan remote add -f gitlab https://gitlab.com/api/v4/packages/conan
    - pipenv run conan install --build missing -o num_collect:requirements_for_tests=True -s build_type=Release ..
    - cd ../

.clang-bench-base:
  extends: .bench-base
  before_script:
    - apt-get update && apt-get install -y ccache
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - pipenv run conan profile new --force --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libc++ default
    - pipenv run conan remote add -f gitlab https://gitlab.com/api/v4/packages/conan
    - pipenv run conan install --build missing -o num_collect:requirements_for_tests=True -s build_type=Release ..
    - cd ../

.clang-debug-test-base:
  extends: .debug-test-base
  before_script:
    - apt-get update && apt-get install -y ccache
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - pipenv run conan profile new --force --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libc++ default
    - pipenv run conan remote add -f gitlab https://gitlab.com/api/v4/packages/conan
    - pipenv run conan install --build missing -o num_collect:requirements_for_tests=True -s build_type=Debug ..
    - cd ../

clang coverage:
  extends: .clang-debug-test-base
  stage: Test with Clang
  image: musicscience37/clang-ci:clang14-v5.0
  variables:
    BUILD_DIR: build_clang_coverage
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
      "-DCMAKE_CXX_FLAGS=-fprofile-instr-generate -fcoverage-mapping"
      "-DCMAKE_MODULE_LINKER_FLAGS=-fprofile-instr-generate -fcoverage-mapping"
      -DNUM_COLLECT_ENABLE_CCACHE:BOOL=ON
    - cd $BUILD_DIR
    - mkdir coverage
    - export LLVM_PROFILE_FILE=$(pwd)/coverage/coverage_%p.profraw
    - cmake --build .
    - ctest -V
    - cd ../
    - scripts/collect_llvm_coverage.sh build_clang_coverage
    - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

gcc coverage:
  extends: .release-test-base
  stage: Test with GCC
  image: musicscience37/gcc-ci:gcc10-v5.0
  variables:
    BUILD_DIR: build_gcc_coverage
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
      "-DCMAKE_CXX_FLAGS=--coverage"
      "-DCMAKE_MODULE_LINKER_FLAGS=--coverage"
      -DNUM_COLLECT_ENABLE_CCACHE:BOOL=ON
    - cd $BUILD_DIR
    - cmake --build .
    - ctest -V
    - cd ../
    - scripts/collect_gcc_coverage.sh build_gcc_coverage
  coverage: '/Total:\|\s*(\d+\.?\d+?)%/'

gcc-10-debug:
  extends: .debug-test-base
  stage: Test with GCC
  image: musicscience37/gcc-ci:gcc10-v5.0
  variables:
    BUILD_DIR: build_gcc10_debug

gcc-10-release:
  extends: .release-test-base
  stage: Test with GCC
  image: musicscience37/gcc-ci:gcc10-v5.0
  variables:
    BUILD_DIR: build_gcc10_release

gcc-10-bench:
  extends: .bench-base
  stage: Test with GCC
  image: musicscience37/gcc-ci:gcc10-v5.0
  variables:
    BUILD_DIR: build_gcc10_bench

clang-14-debug:
  extends: .clang-debug-test-base
  stage: Test with Clang
  image: musicscience37/clang-ci:clang14-v5.0
  variables:
    BUILD_DIR: build_clang14_debug

clang-14-release:
  extends: .clang-release-test-base
  stage: Test with Clang
  image: musicscience37/clang-ci:clang14-v5.0
  variables:
    BUILD_DIR: build_clang14_release

clang-14-bench:
  extends: .clang-bench-base
  stage: Test with Clang
  image: musicscience37/clang-ci:clang14-v5.0
  variables:
    BUILD_DIR: build_clang14_bench

clang-14-asan-ubsan:
  extends: .clang-debug-test-base
  stage: Test with Clang
  image: musicscience37/clang-ci:clang14-v5.0
  variables:
    BUILD_DIR: build_clang_asan_ubsan
    ASAN_OPTIONS: "alloc_dealloc_mismatch=0"
  script:
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
      -DNUM_COLLECT_ENABLE_AUSAN:BOOL=ON
      -DNUM_COLLECT_ENABLE_CCACHE:BOOL=ON
    - cd $BUILD_DIR
    - cmake --build .
    - ctest -V

clang-14-conan:
  extends: .retry setting
  stage: Test with Clang
  needs:
    - sync pipenv
  dependencies:
    - sync pipenv
  image: musicscience37/clang-ci:clang14-v5.0
  variables:
    CONAN_CHANNEL: "testing"
  script:
    - pipenv run conan profile new --force --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libc++ default
    - pipenv run conan remote add -f gitlab https://gitlab.com/api/v4/packages/conan
    - pipenv run conan create --build missing --test-folder test/conan_package . ${CONAN_USER}/${CONAN_CHANNEL}

clang-14-conan-release:
  extends: .retry setting
  stage: Publish
  needs:
    - sync pipenv
  dependencies:
    - sync pipenv
  image: musicscience37/clang-ci:clang14-v5.0
  variables:
    CONAN_CHANNEL: "stable"
  script:
    - pipenv run conan profile new --force --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libc++ default
    - pipenv run conan remote add -f gitlab https://gitlab.com/api/v4/packages/conan
    - pipenv run conan create --build missing --test-folder test/conan_package . ${CONAN_USER}/${CONAN_CHANNEL}
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} pipenv run conan upload -r gitlab num_collect/${NUM_COLLECT_VERSION}@${CONAN_USER}/${CONAN_CHANNEL} --all
  only:
    - tags

.msvc-base:
  extends: .debug-test-base
  tags:
    - shared-windows
    - windows
    - windows-1809
  stage: Test with MSVC
  needs: []
  dependencies: []
  variables:
    CONAN_USER_HOME: C:\Users\gitlab_runner
  before_script:
    - (mv ${CI_PROJECT_DIR}/.conan C:\Users\gitlab_runner -Force)
    - Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
    - choco install cmake -y --installargs 'ADD_CMAKE_TO_PATH=System'
    - choco install python --version=3.9.12 -y
    - choco install ccache -y
    - RefreshEnv
    - ccache --version
    - pip install pipenv
    - pipenv sync
  script:
    # Changed in below.
    - ls
  after_script:
    - (mv C:\Users\gitlab_runner\.conan ${CI_PROJECT_DIR} -Force)
  allow_failure: true

msvc-debug:
  extends: .msvc-base
  variables:
    BUILD_DIR: build_msvc_debug
  script:
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - pipenv run conan profile new --force --detect default
    - pipenv run conan remote add -f gitlab https://gitlab.com/api/v4/packages/conan
    - pipenv run conan install --build missing -o num_collect:requirements_for_tests=True -s build_type=Debug ..
    - cd ../
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Debug
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_ENABLE_UNIT_TESTS=ON
      -DNUM_COLLECT_ENABLE_INTEG_TESTS=OFF
      -DNUM_COLLECT_ENABLE_BENCH=OFF
      -DNUM_COLLECT_TEST_BENCHMARKS=OFF
      -DNUM_COLLECT_BUILD_EXAMPLES=OFF
      -DNUM_COLLECT_TEST_EXAMPLES=OFF
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
      -DNUM_COLLECT_ENABLE_CCACHE:BOOL=ON
      "-DCMAKE_CXX_FLAGS=/DFMT_USE_NONTYPE_TEMPLATE_PARAMETERS=0"
    - cd $BUILD_DIR
    - cmake --build . --config Debug --parallel 3
    - ctest -V --build-config Debug

msvc-release:
  extends: .msvc-base
  variables:
    BUILD_DIR: build_msvc
  script:
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - pipenv run conan profile new --force --detect default
    - pipenv run conan remote add -f gitlab https://gitlab.com/api/v4/packages/conan
    - pipenv run conan install --build missing -o num_collect:requirements_for_tests=True -s build_type=Release ..
    - cd ../
    - cmake -S ./ -B $BUILD_DIR
      -DCMAKE_BUILD_TYPE=Release
      -DNUM_COLLECT_TESTING:BOOL=ON
      -DNUM_COLLECT_ENABLE_UNIT_TESTS=ON
      -DNUM_COLLECT_ENABLE_INTEG_TESTS=OFF
      -DNUM_COLLECT_ENABLE_BENCH=OFF
      -DNUM_COLLECT_TEST_BENCHMARKS=OFF
      -DNUM_COLLECT_BUILD_EXAMPLES=OFF
      -DNUM_COLLECT_TEST_EXAMPLES=OFF
      -DNUM_COLLECT_WRITE_JUNIT:BOOL=ON
      -DNUM_COLLECT_ENABLE_CCACHE:BOOL=ON
      "-DCMAKE_CXX_FLAGS=/DFMT_USE_NONTYPE_TEMPLATE_PARAMETERS=0"
    - cd $BUILD_DIR
    - cmake --build . --config Release --parallel 3
    - ctest -V --build-config Release

doc:
  extends: .retry setting
  stage: Build Documentation
  needs:
    - sync pipenv
  dependencies:
    - sync pipenv
  image: musicscience37/sphinx-doxygen:clang14-v5.0
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - mkdir build_doc
    - cd build_doc
    - pipenv run conan profile new --force --detect default
    - pipenv run conan profile update settings.compiler.libcxx=libstdc++11 default
    - pipenv run conan remote add -f gitlab https://gitlab.com/api/v4/packages/conan
    - pipenv run conan install --build missing -o num_collect:requirements_for_tests=True ..
    - cd ../
    - cmake -S ./ -B build_doc
      -DNUM_COLLECT_BUILD_DOC:BOOL=ON
    - cmake --build build_doc --target num_collect_doc
  artifacts:
    paths:
      - build_doc
    when: always
    expire_in: "3 mos"

pages:
  extends: .retry setting
  stage: Publish
  only:
    - develop
  needs:
    - doc
  dependencies:
    - doc
  script:
    - rm -rf public
    - mv build_doc/doc/html public
  artifacts:
    paths:
      - public
