set(SOURCE_FILES
    compute_kernel_matrix_test.cpp
    compute_polynomial_term_matrix_test.cpp
    concepts/differentiable_rbf_test.cpp
    concepts/fourth_order_differentiable_rbf_test.cpp
    concepts/second_order_differentiable_rbf_test.cpp
    concepts/third_order_differentiable_rbf_test.cpp
    distance_functions/euclidean_distance_function_test.cpp
    gaussian_process_interpolator_test.cpp
    generate_halton_nodes_test.cpp
    impl/differentiate_polynomial_term_test.cpp
    impl/general_spline_equation_solver_test.cpp
    impl/kernel_matrix_solver_test.cpp
    length_parameter_calculators/global_length_parameter_calculator_test.cpp
    length_parameter_calculators/local_length_parameter_calculator_test.cpp
    operators/biharmonic_operator_test.cpp
    operators/function_value_operator_test.cpp
    operators/gradient_operator_test.cpp
    operators/hessian_operator_test.cpp
    operators/laplacian_gradient_operator_test.cpp
    operators/laplacian_operator_test.cpp
    operators/partial_derivative_operator_test.cpp
    operators/third_order_derivative_operator_test.cpp
    polynomial_term_generator_test.cpp
    polynomial_term_test.cpp
    rbf_interpolator_test.cpp
    rbf_polynomial_interpolator_test.cpp
    rbfs/gaussian_from_square_rbf_test.cpp
    rbfs/gaussian_m1_rbf_test.cpp
    rbfs/gaussian_rbf_test.cpp
    rbfs/inverse_multi_quadric_rbf_test.cpp
    rbfs/inverse_quadratic_rbf_test.cpp
    rbfs/multi_quadric_rbf_test.cpp
    rbfs/polyharmonic_spline_rbf_test.cpp
    rbfs/sech_rbf_test.cpp
    rbfs/thin_plate_spline_rbf_test.cpp
    rbfs/wendland_csrbf_test.cpp
)
