@startuml implicit_formulas

title Abstract Model of Implicit Runge-Kutta Method

package ode {
    !includesub ../formula_and_problems.puml!formula
    !includesub ../embedded_formulas.puml!embedded_formula
    !includesub ../embedded_formulas.puml!error_tolerances
    formula <|- embedded_formula

    package runge_kutta {

        class stage_equation_solver<Problem> {
            + solve(problem: problem_type&,\n\ttime: scalar_type, step_size: scalar_type,\n\tvariable: const variable_type&, k_coeff: scalar_type)
            + k() : const variable_type&
            + tol_residual_norm(val: scalar_type)
        }
        stage_equation_solver o-- error_tolerances

        class implicit_formula_solver_coeffs {
            {static} + stages: index_type
            {static} + a: array<array<scalar_type, stages>, stages>
            {static} + b: array<scalar_type, stages>
        }

        class step_equation_solver<Problem, Coeffs> {
            + solve(problem: problem_type&,\n\ttime: scalar_type, step_size: scalar_type,\n\tvariable: const variable_type&)
            + k(index: index_type) : const variable_type&
            + tol_residual_norm(val: scalar_type)
        }
        step_equation_solver ..> implicit_formula_solver_coeffs

        ' These may be implemented in the future.
        remove implicit_formula_solver_coeffs
        remove step_equation_solver

        class implicit_formula<Problem> {
            + tol_rel_residual_norm(val: scalar_type)
            + tol_abs_residual_norm(val: scalar_type)
        }
        formula <|-- implicit_formula
        implicit_formula o-- stage_equation_solver
        implicit_formula o-- step_equation_solver

        class implicit_embedded_formula<Problem> {
        }
        implicit_formula <|- implicit_embedded_formula
        embedded_formula <|-- implicit_embedded_formula

        note as implicit_formula_solver_selection_note
            Actually one of these are used in implicit_formula
            depending on formulas.
        end note
        implicit_formula_solver_selection_note .. stage_equation_solver
        implicit_formula_solver_selection_note .. step_equation_solver
        implicit_formula_solver_selection_note .up. implicit_formula

    }
}

@enduml
