set(SOURCE_FILES
    assert_test.cpp
    bidirectional_vector_test.cpp
    exception_test.cpp
    get_size_test.cpp
    is_eigen_matrix_test.cpp
    is_eigen_vector_test.cpp
    iteration_logger_test.cpp
    kahan_adder_test.cpp
    norm_test.cpp
    safe_cast_test.cpp
    source_info_view_test.cpp
)
