#include "de_finite_integrator_test.cpp"
#include "de_infinite_integrator_test.cpp"
#include "de_semi_infinite_integrator_test.cpp"
#include "gauss_legendre_integrator_test.cpp"
#include "gauss_legendre_kronrod_integrator_test.cpp"
#include "tanh_finite_integrator_test.cpp"
