#include "de_finite_integrator_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "de_infinite_integrator_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "de_semi_infinite_integrator_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "gauss_legendre_integrator_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "gauss_legendre_kronrod_integrator_test.cpp"  // NOLINT(bugprone-suspicious-include)
