# Example configuration to write to console and file asynchronously.

# Default configuration for log tags. (Optional.)
[[num_collect.logging.tag_configs]]

# Log tag. (Required.)
# Empty string specifies the default configuration.
tag = ""

# Name of a log sink. (Optional.)
# Log sink with this name must be configured in
# num_collect.logging.sinks configuration (written below) in the same file,
# or use "default" log sink in this library.
sink = "async sink"

# Minimum log level to output. (Optional.)
# Choices: trace, debug, iteration, summary, info, warning, error, critical, off.
output_log_level = "trace"

# Minimum log level to output in child iterations. (Optional.)
# Choices are same as output_log_level.
output_log_level_in_child_iterations = "info"

# Period to write iteration logs. (Optional.)
iteration_output_period = 10

# Period to write labels of iteration logs. (Optional.)
iteration_label_period = 20

# Asynchronous log sink.
[[num_collect.logging.sinks]]

# Name of the log sink. (Required.)
name = "async sink"

# Type of the log sink. (Required.)
type = "async"

# Log sink used to actual logging in asynchronous processing. (Required.)
# A log sink with this name must be configured in the same file.
inner_sink_name = "console file sink"

# Combined log sink to write to console and file.
[[num_collect.logging.sinks]]

# Name of the log sink. (Required.)
name = "console file sink"

# Type of the log sink. (Required.)
type = "combined"

# Log sinks used to actual logging. (Required.)
# Log sink with these names must be configured in the same file.
inner_sink_names = ["file sink", "console sink"]

# Minimum log levels to output. (Required.)
# Number of elements must be same with inner_sink_names.
output_log_levels = ["trace", "info"]

# Log sink to write to console.
[[num_collect.logging.sinks]]

# Name of the log sink. (Required.)
name = "console sink"

# Type of the log sink. (Required.)
type = "console"

# Whether to use color. (Optional.)
use_color = true

# Log sink to write to a single file.
[[num_collect.logging.sinks]]

# Name of the log sink. (Required.)
name = "file sink"

# Type of the log sink. (Required.)
type = "single_file"

# Filepath. (Required.)
filepath = "num_collect_ex_write_logs.log"
