# Example configuration to use the default log sink (a log sink to write to console).

# Schema.
"$schema" = "https://numcollect.musicscience37.com/config_schema/v2/config_schema.json"

# Default configuration for log tags. (Optional.)
[[num_collect.logging.tag_configs]]

# Log tag. (Required.)
# Empty string specifies the default configuration.
tag = ""

# Name of a log sink. (Optional.)
# Log sink with this name must be configured in
# num_collect.logging.sinks configuration (written below) in the same file,
# or use "default" log sink in this library.
sink = "default"

# Minimum log level to output. (Optional.)
# Choices: trace, debug, iteration, summary, info, warning, error, critical, off.
output_log_level = "iteration"

# Minimum log level to output in child iterations. (Optional.)
# Choices are same as output_log_level.
output_log_level_in_child_iterations = "info"

# Period to write iteration logs. (Optional.)
iteration_output_period = 10

# Period to write labels of iteration logs. (Optional.)
iteration_label_period = 20
