# Example configuration to write to a file asynchronously.

# Schema.
"$schema" = "https://numcollect.musicscience37.com/config_schema/v3/config_schema.json"

# Default configuration for log tags. (Optional.)
[[num_collect.logging.tag_configs]]

# Log tag. (Required.)
# Empty string specifies the default configuration.
tag = ""

# Name of a log sink. (Optional.)
# Log sink with this name must be configured in
# num_collect.logging.sinks configuration (written below) in the same file,
# or use "default" log sink in this library.
sink = "async file sink"

# Minimum log level to output. (Optional.)
# Choices: trace, debug, iteration, summary, info, warning, error, critical, off.
output_log_level = "iteration"

# Minimum log level to output in child iterations. (Optional.)
# Choices are same as output_log_level.
output_log_level_in_child_iterations = "info"

# Period to write iteration logs. (Optional.)
iteration_output_period = 10

# Period to write labels of iteration logs. (Optional.)
iteration_label_period = 20

[[num_collect.logging.sinks]]

# Name of the log sink. (Required.)
name = "file sink"

# Type of the log sink. (Required.)
type = "single_file"

# Filepath. (Required.)
filepath = "example_logging_write_logs.log"

[[num_collect.logging.sinks]]

# Name of the log sink. (Required.)
name = "async file sink"

# Type of the log sink. (Required.)
type = "async"

# Log sink used to actual logging. (Required.)
# Log sink with this name must be configured in the same file.
inner_sink_name = "file sink"
