set(SOURCE_FILES
    dimensions/gaussian_process_interpolator.cpp
    dimensions/global_rbf_polynomial_interpolator.cpp
    dimensions/local_csrbf_interpolator.cpp
    dimensions/local_rbf_interpolator.cpp
    operators/derivative.cpp
    operators/fourth_derivative.cpp
    operators/second_derivative.cpp
    operators/third_derivative.cpp
    rbfs/gaussian_process_interpolator.cpp
    rbfs/global_rbf_polynomial_interpolator.cpp
    rbfs/local_csrbf_interpolator.cpp
    rbfs/local_rbf_interpolator.cpp
)
