set(SOURCE_FILES
    kernel/calc_kernel_mat_test.cpp
    kernel/euclidean_distance_test.cpp
    kernel/gaussian_rbf_test.cpp
    kernel/impl/auto_regularizer_test.cpp
    kernel/impl/auto_regularizer_wrapper_test.cpp
    kernel/impl/kernel_parameter_optimizer_test.cpp
    kernel/impl/self_adjoint_kernel_solver_test.cpp
    kernel/kernel_interpolator_test.cpp
    kernel/rbf_kernel_test.cpp
)
