set(SOURCE_FILES
    exponential/embedded.cpp
    exponential/non_embedded.cpp
    external_force_vibration_problem.h/embedded.cpp
    external_force_vibration_problem.h/non_embedded.cpp
    implicit_exponential/embedded.cpp
    implicit_kaps/embedded.cpp
    spring_movement/embedded.cpp
    spring_movement/non_embedded.cpp
)
