set(SOURCE_FILES
    changing_mass_exponential/embedded.cpp
    exponential/embedded.cpp
    exponential/non_embedded.cpp
    external_force_vibration_problem.h/embedded.cpp
    external_force_vibration_problem.h/non_embedded.cpp
    implicit_exponential/embedded.cpp
    implicit_kaps/embedded.cpp
    no_jacobian_implicit_kaps_problem/embedded.cpp
    spring_movement/embedded.cpp
    spring_movement/non_embedded.cpp
    spring_movement/wrapped_non_embedded.cpp
)
