"""Generate plot_colors.idp for color maps used in FreeFEM."""

import pathlib

import colour
import ok_palette_lab.plotly

THIS_DIR = pathlib.Path(__file__).absolute().parent
PLOT_COLORS_FILE = THIS_DIR / "plot_colors.idp"


def convert_color_str_to_hsv(color_str: str) -> tuple[float, float, float]:
    """16 進数カラーコードをHSVに変換する。"""
    rgb = colour.notation.HEX_to_RGB(color_str)
    hsv = colour.RGB_to_HSV(rgb)
    return hsv  # type: ignore


def generate_plot_colors() -> None:
    """プロット用のカラーマップのファイルを生成する。"""
    origin = ok_palette_lab.plotly.tea
    color_str_list = [pair[1] for pair in origin]
    hsv_list = [convert_color_str_to_hsv(color_str) for color_str in color_str_list]

    with open(str(PLOT_COLORS_FILE), "w", encoding="utf-8") as file:
        file.write("// This file is auto-generated by generate_plot_colors.py\n")
        file.write("real[int] PlotColors = [\n")
        joined_colors = ",\n".join(
            f"    {hue}, {saturation}, {value}" for hue, saturation, value in hsv_list
        )
        file.write(joined_colors)
        file.write("\n];\n")


if __name__ == "__main__":
    generate_plot_colors()
