#include "compile_time_legendre_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "gamma_test.cpp"               // NOLINT(bugprone-suspicious-include)
#include "impl/gamma_lanczos_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "legendre_roots_test.cpp"      // NOLINT(bugprone-suspicious-include)
#include "legendre_test.cpp"            // NOLINT(bugprone-suspicious-include)
