[ct_simulation]
# Size of the image. (Rows and columns of the image.)
image_size = 40
# Number of directions of centers of rays.
num_directions = 9
# Number of rays per direction.
num_rays_per_direction = 16
# Noise rate.
noise_rate = 1e-6
# Index of the sample image to be generated.
# 1: One constant circle.
# 2: Two constant circles.
# 3: One quadratic circle.
# 4: One smooth circle.
# 5: Two smooth circles.
sample_image_index = 5

# Configurations of numerical-collection-cpp library.
"$schema" = "https://numcollect.musicscience37.com/config_schema/v2/config_schema.json"

[[num_collect.logging.tag_configs]]
tag = ""
output_log_level = "debug"
output_log_level_in_child_iterations = "warning"

[[num_collect.logging.tag_configs]]
tag = "num_collect::opt::gaussian_process_optimizer"
iteration_output_period = 1

# Enable following configuration for more logging.
[[num_collect.logging.tag_configs]]
tag = "num_collect::regularization::tv_admm"
output_log_level_in_child_iterations = "summary"
# [[num_collect.logging.tag_configs]]
# tag = "num_collect::regularization::tgv2_admm"
# output_log_level_in_child_iterations = "summary"
