set(SOURCE_FILES
    avf/avf2_formula_test.cpp
    avf/avf3_formula_test.cpp
    avf/avf4_formula_test.cpp
    basic_step_size_controller_test.cpp
    embedded_solver_test.cpp
    error_tolerances_test.cpp
    evaluation_type_test.cpp
    impl/get_least_known_order_test.cpp
    inexact_newton_slope_equation_solver_test.cpp
    inexact_newton_update_equation_solver_test.cpp
    initial_step_size_calculator_test.cpp
    non_embedded_formula_wrapper_test.cpp
    pi_step_size_controller_test.cpp
    rosenbrock/default_rosenbrock_equation_solver_test.cpp
    rosenbrock/lu_rosenbrock_equation_solver_test.cpp
    rosenbrock/mixed_broyden_rosenbrock_equation_solver_test.cpp
    rosenbrock/rodasp_formula_test.cpp
    rosenbrock/rodaspr_formula_test.cpp
    rosenbrock/ros34pw3_formula_test.cpp
    rosenbrock/ros3w_formula_test.cpp
    rosenbrock/scalar_rosenbrock_equation_solver_test.cpp
    runge_kutta/ark43_esdirk_formula_test.cpp
    runge_kutta/ark54_esdirk_formula_test.cpp
    runge_kutta/dopri5_formula_test.cpp
    runge_kutta/implicit_euler_formula_test.cpp
    runge_kutta/rk4_formula_test.cpp
    runge_kutta/rkf45_formula_test.cpp
    runge_kutta/sdirk4_formula_test.cpp
    runge_kutta/tanaka1_formula_test.cpp
    runge_kutta/tanaka2_formula_test.cpp
    simple_solver_test.cpp
    step_size_limits_test.cpp
)
