set(SOURCE_FILES
    avf/avf2_formula_test.cpp
    avf/avf3_formula_test.cpp
    avf/avf4_formula_test.cpp
    embedded_solver_test.cpp
    error_tolerances_test.cpp
    evaluation_type_test.cpp
    non_embedded_formula_wrapper_test.cpp
    runge_kutta/implicit_euler_formula_test.cpp
    runge_kutta/rk4_formula_test.cpp
    runge_kutta/rkf45_formula_test.cpp
    runge_kutta/ros34pw3_formula_test.cpp
    runge_kutta/ros3w_formula_test.cpp
    runge_kutta/semi_implicit_formula_solver_test.cpp
    runge_kutta/tanaka1_formula_test.cpp
    runge_kutta/tanaka2_formula_test.cpp
    simple_solver_test.cpp
    step_size_limits_test.cpp
)
