set(SOURCE_FILES
    algebraic_multigrid_solver_test.cpp
    cuthill_mckee_ordering_test.cpp
    gauss_seidel_iterative_solver_test.cpp
    impl/amg/build_first_coarse_grid_candidate_test.cpp
    impl/amg/compute_strong_connection_list_test.cpp
    impl/amg/create_coarse_grid_test.cpp
    impl/amg/create_prolongation_matrix_test.cpp
    impl/amg/node_connection_list_test.cpp
    impl/amg/tune_coarse_grid_selection_test.cpp
    impl/operator_conjugate_gradient_test.cpp
    parallel_symmetric_successive_over_relaxation.cpp
    reverse_cuthill_mckee_ordering_test.cpp
    symmetric_successive_over_relaxation.cpp
)
