#include "cuthill_mckee_ordering_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "gauss_seidel_iterative_solver_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "impl/compute_strong_connection_list_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "impl/node_connection_list_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "parallel_symmetric_successive_over_relaxation.cpp"  // NOLINT(bugprone-suspicious-include)
#include "reverse_cuthill_mckee_ordering_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "symmetric_successive_over_relaxation.cpp"  // NOLINT(bugprone-suspicious-include)
