set(SOURCE_FILES
    concepts/getter_of_test.cpp
    formatters/colored_compact_log_formatter_test.cpp
    formatters/detailed_log_formatter_test.cpp
    formatters/get_log_level_str_for_log_test.cpp
    formatters/iso8601_time_test.cpp
    impl/iteration_layer_handler_test.cpp
    impl/load_logging_config_toml_test.cpp
    impl/log_formatter_test.cpp
    impl/log_tag_config_tree_test.cpp
    impl/log_tag_element_test.cpp
    impl/separate_top_log_tag_element_test.cpp
    iteration_logger_test.cpp
    load_logging_config_test.cpp
    log_config_test.cpp
    log_level_test.cpp
    log_tag_config_test.cpp
    log_tag_test.cpp
    log_tag_view_test.cpp
    logger_test.cpp
    logging_mixin_test.cpp
    simple_log_sink_test.cpp
)
