set(SOURCE_FILES
    concepts/getter_of_test.cpp
    config/log_sink_factory_table_test.cpp
    config/toml/toml_async_log_sink_config_parser_test.cpp
    config/toml/toml_combined_log_sink_config_parser_test.cpp
    config/toml/toml_console_log_sink_config_parser_test.cpp
    config/toml/toml_helper_test.cpp
    config/toml/toml_log_config_parser_test.cpp
    config/toml/toml_single_file_log_sink_config_parser_test.cpp
    formatters/colored_compact_log_formatter_test.cpp
    formatters/compact_log_formatter_test.cpp
    formatters/detailed_log_formatter_test.cpp
    formatters/get_log_level_str_for_log_test.cpp
    formatters/iso8601_time_test.cpp
    impl/iteration_layer_handler_test.cpp
    impl/log_tag_config_tree_test.cpp
    impl/log_tag_element_test.cpp
    impl/separate_top_log_tag_element_test.cpp
    iteration_logger_test.cpp
    iterations/iteration_parameter_test.cpp
    iterations/iteration_paramter_formatter_test.cpp
    iterations/variable_iteration_parameter_value_test.cpp
    load_logging_config_test.cpp
    log_config_test.cpp
    log_level_test.cpp
    log_tag_config_test.cpp
    log_tag_test.cpp
    log_tag_view_test.cpp
    logger_test.cpp
    logging_mixin_test.cpp
    sinks/async_log_sink_test.cpp
    sinks/async_logging_worker_test.cpp
    sinks/combined_log_sink_test.cpp
    sinks/file_wrapper_test.cpp
    sinks/simple_log_sink_test.cpp
)
