#include "impl/log_formatter_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "log_config_test.cpp"          // NOLINT(bugprone-suspicious-include)
#include "log_level_test.cpp"           // NOLINT(bugprone-suspicious-include)
#include "log_tag_config_test.cpp"      // NOLINT(bugprone-suspicious-include)
#include "log_tag_test.cpp"             // NOLINT(bugprone-suspicious-include)
#include "log_tag_view_test.cpp"        // NOLINT(bugprone-suspicious-include)
#include "simple_log_sink_test.cpp"     // NOLINT(bugprone-suspicious-include)
