set(SOURCE_FILES
    adaptive_diagonal_curves_test.cpp
    annealing_downhill_simplex_test.cpp
    any_objective_function_test.cpp
    backtracking_line_searcher_test.cpp
    bfgs_optimizer_test.cpp
    conjugate_gradient_optimizer_test.cpp
    dfp_optimizer_test.cpp
    dividing_rectangles_test.cpp
    downhill_simplex_test.cpp
    firefly_optimizer_test.cpp
    function_object_wrapper_test.cpp
    gaussian_process_optimizer_test.cpp
    golden_section_search_test.cpp
    heuristic_global_optimizer_test.cpp
    impl/adc_group_test.cpp
    impl/adc_rectangle_test.cpp
    impl/adc_sample_dict_test.cpp
    impl/adc_ternary_vector_test.cpp
    newton_optimizer_test.cpp
    real_value_genetic_optimizer_test.cpp
    sampling_optimizer_test.cpp
    steepest_descent_test.cpp
)
